### PR TITLE
Error code "timeout-or-duplicate" added. Made tests pass ok. Updated documentation.

### PR DESCRIPTION
**Pull request by neoneye**
Thanks for this awesome project.

---
This change is [Reviewable](https://reviewable.io/reviews/panicbit/recaptcha-rs/8)

### CODE REVIEW

**Comment by panicbit** [comment]
Well, thank you for the contribution! 😃
I will try to have a look at it this evening (in ~4 hours).

**Comment by panicbit** [comment]
Taking a look now.

**Comment by panicbit** [comment]
Looks good.
I'll have to do a minor version bump, since adding that enum variant is a breaking change.

**Comment by panicbit** [comment]
Published `0.5.0` on crates.io

**Comment by neoneye** [comment]
Wow, fast! Thank you  @panicbit much appreciated.

**Pull request merged**
